version: 0.2

#run-as: codebuild-user

env:
  shell: /bin/bash

phases:
  install:
    on-failure: ABORT 
    commands:
      - pip3 install mkdocs
      - pip3 install mkdocs-material
      - pip3 install mkdocs-minify-plugin
      - pip3 install mkdocs-git-revision-date-localized-plugin
  #pre_build:
  #  run-as: Linux-user-name
  #  on-failure: ABORT | CONTINUE
  #  commands:
  #    - command
  #    - command
  #  finally:
  #    - command
  #    - command
  build:
    #run-as: Linux-user-name
    #on-failure: ABORT
    commands:
      - cd mkdocs
      - mkdocs build
   # finally:
   #   - command
   #   - command
  #post_build:
  #  run-as: Linux-user-name
  #  on-failure: ABORT | CONTINUE
  #  commands:
  #    - command
  #    - command
  #  finally:
  #    - command
  #    - command
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
artifacts:
  files:
    - '**/*'
  base-directory: 'mkdocs/site'
#  name: artifact-name
#  discard-paths: no | yes
#  base-directory: location
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
