version: 0.2

#run-as: codebuild-user

env:
  shell: /bin/bash

phases:
  install:
    on-failure: ABORT 
    commands:
      - pip3 install mkdocs
      - pip3 install mkdocs-material
      - pip3 install mkdocs-minify-plugin
      - pip3 install mkdocs-git-revision-date-localized-plugin
      - apt update
      - apt install -y libfuse2 libatk1.0-0 libatk-bridge2.0-0 libcups2 libgtk-3-0 libnss3 libxss1 libasound2 libdbus-glib-1-2 libgconf-2-4 libnotify4
  #pre_build:
  #  run-as: Linux-user-name
  #  on-failure: ABORT | CONTINUE
  #  commands:
  #    - command
  #    - command
  #  finally:
  #    - command
  #    - command
  build:
    #run-as: Linux-user-name
    #on-failure: ABORT
    commands:
      - bash drawio-export.sh
      - cd mkdocs
      - mkdocs build
   # finally:
   #   - command
   #   - command
  post_build:
  #  run-as: Linux-user-name
  #  on-failure: ABORT | CONTINUE
    commands:
      - export BUILD_DATE_TIME=$(date +'%Y_%m_%d-%H_%M')
      - export GIT_SHORT_HASH=$(git rev-parse --short HEAD)
      - pwd
      - ls -lhtra
      - env | sort
  #  finally:
  #    - command
  #    - command
#reports:
#  report-group-name-or-arn:
#    files:
#      - location
#      - location
#    base-directory: location
#    discard-paths: no | yes
#    file-format: report-format
artifacts:
  files:
    - '**/*'
  base-directory: 'mkdocs/site'
  name: mega_resume-${BUILD_DATE_TIME}-${GIT_SHORT_HASH}
#  discard-paths: no | yes
#  base-directory: location
#  exclude-paths: excluded paths
#  enable-symlinks: no | yes
#  s3-prefix: prefix
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
