site_name: Gabriel P. Silva
site_url: https://psilva.org/
site_author: Gabriel P. Silva
site_description: >-
  Gabriel's resume. The DevOps engineer

  # Repository
repo_name: gabepsilva/gabriel
repo_url: https://github.com/gabepsilva/gabriel

# Copyright
copyright: Copyright &copy; 2016 - 2023 Gabriel da Silva

nav:
  - Home: index.md
  - <strong>Projects</strong>: /
  - Mega Resume: projects/mega-resume/resume.md
  

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gabrielpe

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.tasklist:
      #clickable_checkbox: true
      custom_checkbox: true

  - admonition
  - pymdownx.details

  - attr_list
  - md_in_html



# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  #- git-revision-date-localized
